#!/usr/bin/env ruby

require 'tx'
require 'optparse'

options_parser = OptionParser.new do |opts| 
    opts.banner = 'help message'
    txdb = DeleteBranch.new()
    opts.on('-l args', '--local args', 'delete local branch') do |value|
        txdb.delete_local(value, false)
    end

    opts.on('-L args', '--Local args', 'force delete local branch') do |value|
        txdb.delete_local(value, true)
    end

    opts.on('-r args', '--remote args', 'remote branch') do |value|
        txdb.delete_remote(value)
    end

    opts.on('-a args', '--all args', 'local & remote branch') do |value|
        txdb.delete_local(value, false)
        txdb.delete_remote(value)
    end
end.parse!
#txdb = TX::DeleteBranch.new()


