#!/usr/bin/env ruby

require 'tx'
require 'optparse'

options_parser = OptionParser.new do |opts| 
    opts.banner = 'help message'
    txdb = DeleteBranch.new()
    opts.on('-l args', '--local args', 'delete local branch') do |value|
        if TXArgParser.gitBrIsValid(value)
            txdb.delete_local(value, false)
        else
            TXArgParser.gitBrInvalidMessage(value)
        end
    end

    opts.on('-L args', '--Local args', 'force delete local branch') do |value|
        if TXArgParser.gitBrIsValid(value)
            txdb.delete_local(value, true)
        else
            TXArgParser.gitBrInvalidMessage(value)
        end
    end

    opts.on('-r args', '--remote args', 'remote branch') do |value|
        if TXArgParser.gitBrIsValid(value)
            txdb.delete_remote(value)
        else
            TXArgParser.gitBrInvalidMessage(value)
        end
    end

    opts.on('-a args', '--all args', 'local & remote branch') do |value|
        if TXArgParser.gitBrIsValid(value)
            txdb.delete_local(value, false)
            txdb.delete_remote(value)
        else
            TXArgParser.gitBrInvalidMessage(value)
        end
    end
end.parse!


